### ISSUE TITLE
Idea: use files from the pipeline as input

### ISSUE THREAD

**Issue by ninmonkey** [santisq/PSTree#6]
Instead recursing all files, only include those that are explicitly passed in. This lets you be flexible, having the ability to use any pre-filtering. 

## Ex1: [IO.FileSystemInfo[]]
```ps1
Get-ChildItem -recurse
| ?{ $_.LastWriteTime -lt (get-date).addDays(-90) }
| PSTree
```
## Ex2: [String[]] from native commands

When Paths are raw text
```ps1
fd -e ps1
| PSTree
```
## Ex3: PSTree instances

```ps1
$query = GPSTree .
$query

# Filter to the largest 10 files
$res | sort RawSize
| select-object -First 10
| GPSTree
```
The new render and total size only includes the first 10 largest files

screenshot from `as-tree` . this program is raw text, having objects would be nice. 

![image](https://user-images.githubusercontent.com/3892031/172496587-2db53d78-676e-4cfd-924b-ea389ac2d5dc.png)

**Comment by santisq** [comment]
@ninmonkey planning to add `-Filter` in future release that would share same functionality as `Get-ChildItem`.

- Regarding the 1st example, the function already has a hidden property that contains the IO instance of the original objects, so using `Get-ChildItem` to then pipe into `Get-PSTree` is not needed or efficient. The filtering is possible doing:

```powershell
pstree -Recurse | ? { $_.Instance.LastWriteTime -lt [datetime]::Now.AddDays(-90) }
```

- Regarding the 2nd example, the function is already able to take input from pipeline, as long as the native commands are outputting an absolute or valid relative path that should work fine.
- Regarding the 3rd example, I like the idea and will likely try to implement it in future release though worth noting this would only work as long as the files share the hierarchy in my opinion, otherwise there is no way I can think of to properly draw the hierarchy tree
